"""Add polls tables

Revision ID: 0d39d56db942
Revises: 
Create Date: 2025-10-03 16:09:53.705792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d39d56db942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table('poll'):
        op.create_table('poll',
        sa.Column('id', sa.String(length=8), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('creator_token', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not inspector.has_table('poll_movie'):
        op.create_table('poll_movie',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('poll_id', sa.String(length=8), nullable=False),
        sa.Column('kinopoisk_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('search_name', sa.String(length=200), nullable=True),
        sa.Column('poster', sa.String(length=500), nullable=True),
        sa.Column('year', sa.String(length=10), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rating_kp', sa.Float(), nullable=True),
        sa.Column('genres', sa.String(length=200), nullable=True),
        sa.Column('countries', sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not inspector.has_table('vote'):
        op.create_table('vote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('poll_id', sa.String(length=8), nullable=False),
        sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column('voter_token', sa.String(length=32), nullable=False),
        sa.Column('voted_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['movie_id'], ['poll_movie.id'], ),
        sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('poll_id', 'voter_token', name='unique_voter_per_poll')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('poll_movie')
    op.drop_table('poll')
    # ### end Alembic commands ###
