"""add_badge_to_library_movie

Revision ID: f3443ff64408
Revises: 0d39d56db942
Create Date: 2025-10-08 15:28:01.108829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3443ff64408'
down_revision = '0d39d56db942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'badge' not in {col['name'] for col in inspector.get_columns('library_movie')}:
        op.add_column('library_movie', sa.Column('badge', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'badge' in {col['name'] for col in inspector.get_columns('library_movie')}:
        op.drop_column('library_movie', 'badge')
    # ### end Alembic commands ###
